import type { ArgsDef } from "citty";

export const commonArgs = {
	workflow: { type: "string" },
	"session-id": { type: "string" },
	cwd: { type: "string" },
	"plot-dir": { type: "string" },
	"agent-dir": { type: "string" },
	"session-dir": { type: "string" },
	"log-level": { type: "string" },
	"log-format": { type: "string" },
	"request-queue-capacity": { type: "string" },
	"event-capacity": { type: "string" },
	"replay-capacity": { type: "string" },
	"tick-interval-ms": { type: "string" },
	"max-run-duration-ms": { type: "string" },
	provider: { type: "string" },
	model: { type: "string" },
	"api-key": { type: "string" },
	thinking: { type: "string" },
	tools: { type: "string" },
	"exclude-tools": { type: "string" },
	"no-tools": { type: "boolean" },
	"no-builtin-tools": { type: "boolean" },
	approve: { type: "boolean" },
	skill: { type: "string" },
	"prompt-template": { type: "string" },
	"no-skills": { type: "boolean" },
	"no-prompt-templates": { type: "boolean" },
	"no-context-files": { type: "boolean" },
	"system-prompt": { type: "string" },
	"append-system-prompt": { type: "string" },
} satisfies ArgsDef;
